### ISSUE TITLE
Version on Hackage does not compile with ghc-9.6.1

### ISSUE THREAD

**Issue by erikd** [stevenfontanella/microlens#168]
When I try I get:
```
Configuring library for microlens-th-0.2.0.0..
Preprocessing library for microlens-th-0.2.0.0..
Building library for microlens-th-0.2.0.0..
[1 of 1] Compiling Lens.Micro.TH    ( src/Lens/Micro/TH.hs, dist/build/Lens/Micro/TH.o, dist/build/Lens/Micro/TH.dyn_o )

src/Lens/Micro/TH.hs:504:18: error: [GHC-83865]
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the first argument of ‘HasName’, namely ‘TyVarBndr’
      In the instance declaration for ‘HasName TyVarBndr’
    |
504 | instance HasName TyVarBndr where
    |                  ^^^^^^^^^

src/Lens/Micro/TH.hs:524:22: error: [GHC-83865]
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the first argument of ‘HasTypeVars’, namely ‘TyVarBndr’
      In the instance declaration for ‘HasTypeVars TyVarBndr’
    |
524 | instance HasTypeVars TyVarBndr where
    |                      ^^^^^^^^^
Error: cabal: Failed to build microlens-mtl-0.1.3.0 (which is required by
exe:debugger from plutus-core-1.5.0.0). See the build log above for details.
Failed to build microlens-th-0.2.0.0 (which is required by exe:debugger from
plutus-core-1.5.0.0). See the build log above for details.
```
Looks like this is due to changes in the template haskell interface.

**Comment by erikd** [comment]
I think all that is needed is a release to Hackage.

**Comment by stevenfontanella** [comment]
You're trying to build very old versions of `microlens-mtl` (`0.1.3.0`, current version is `0.2.0.3`) and `microlens-th` (`0.2.0.0`, current version is `0.4.3.12`). Only the latest version of microlens-th supports GHC 9.6.1.

I see from your logs that these are prerequisites for `plutus-core-1.5.0.0`, you should check if a later version of plutus-core allows higher microlens bounds, or try to bump the version bounds yourself.

I'll close this, but feel free to reopen if you have other issues.

**Comment by stevenfontanella** [comment]
@erikd I checked out of curiosity, looks like plutus-core doesn't even specify a bound on microlens + microlens-th [link](https://github.com/input-output-hk/plutus/blob/master/plutus-core/plutus-core.cabal#L691). My guess is that your cabal repo is out of date, maybe try `cabal v2-update` and build again?

**Comment by erikd** [comment]
Sorry, I should have close this issue when I figured it out. All sorted now. Thanks.
